INSERT INTO `resource`
    (`id`, `name`, `description`)
VALUES
    ('1', 'corn','Money, ideals, religion - all does not matter. Without food you are dead.'),
    ('2', 'eggs','They roll out from the strange building.'),
    ('3', 'chickens','Future workers , future fighters.'),
    ('4', 'dung','It shall be useful in the future. lets save some in warehouse.'),
    ('5', 'hens','Lay some eggs for me baby! They will become cocks in future. Strange logic.'),
    ('6', 'cocks','Mighty warriors (in future).'),
    ('7', 'fighting cocks','They can fight, they can kill, they can sprinkle you with dung.'),
    ('8', 'stone','The first material of ancient war'),
    ('9', 'cocks with hammers','They crush their enemy to pancake with feathers.'),
    ('10', 'cocks with slingshots','They can shoot enemy ass from the bushes.'),
    ('11', 'steel','Mighty, heavy, hard and very useful in war, material'),
    ('12', 'cocks swordsmen (in lats)','Knights of chicken world.'),
    ('13', 'cocks with axes (in lats)','Barbarians every where are the same.'),
    ('14', 'wood','Not long ago, it was a beautiful forest. Now it is material'),
    ('15', 'cocks archers','Bows and crossbows are those wifes.'),
    ('16', 'cocks lancers','They will nail enemy on lance.'),
    ('17', 'gunpowder','War... War never changes. Gunpowder, who got it - got victory'),
    ('18', 'cocks gunners','Heavy machine guns, rifles and pistols. They have a lot of them.'),
    ('19', 'cocks with bazookas','One shot... all dead.'),
    ('20', 'mana essence','The key to understand the world, and the key to destroy it.'),
    ('21', 'cocks magicians','Almighty archmages in feathers. They can burn, froze and make dung storms.'),
    ('22', 'cocks prophets','The word of prophet is the rule. They can see future and curse enemy to death.'),
    ('23', 'experience','Number if scars on every cock.'),
    ('24', 'cockiness','Someone call this morale, someone - madness it does not mater.')