INSERT INTO `building`
    (`id`, `name`,`description`)
VALUES
    ('1', 'Granary', 'The most mysterious building. It makes food from nothing.'),
    ('2', 'Chicken House', 'Produce eggs'),
    ('3', 'Incubator', 'Produce chickens'),
    ('4', 'Cleaning Center', 'Produce dung'),
    ('5', 'Chicken Yard', 'Produce hens'),
    ('6', 'Cocks House', 'Produce cocks'),
    ('7', 'Cocks Barrack', 'Produce fighting cocks'),
    ('8', 'Quarry', 'Produce stone'),
    ('9', 'School of Hammers', 'Produce cocks with hammers'),
    ('10', 'School of Slingshots', 'Produce cocks with slingshots'),
    ('11', 'Blast Furnace', 'Produce steel'),
    ('12', 'School of Swordsmen', 'Produce cocks swordsmen (in lats)'),
    ('13', 'School of Axes', 'Produce cocks with axes (in lats)'),
    ('14', 'Logger', 'Produce wood'),
    ('15', 'School of Archers', 'Produce cocks archers'),
    ('16', 'School of Lancers', 'Produce cocks lancers'),
    ('17', 'Alchemy Laboratory', 'Produce gunpowder'),
    ('18', 'School of Gunners', 'Produce cocks gunners'),
    ('19', 'School of Bazookas', 'Produce cocks with bazookas'),
    ('20', 'Altar', 'Produce mana essence'),
    ('21', 'School of Magic', 'Produce cocks magicians'),
    ('22', 'Zikkurat', 'Produce cocks prophets')