insert INTO Resource
            (id, name, description)
VALUES
(1, 'Corn', 'Corn value'),
(2, 'Eggs', 'Eggs value'),
(3, 'Chickens', 'Chickens value'),
(4, 'Dung', 'Dung value'),
(5, 'Hens', 'Hens value'),
(6, 'Cocks', 'Cocks value'),
(7, 'Fighting cocks', 'Fighting cocks value'),
(8, 'Stone', 'Stone value'),
(9, 'Cocks with hammers', 'Cocks with hammers value'),
(10, 'Cocks with slingshots', 'Cocks with slingshots value'),
(11, 'Steel', 'Steel value'),
(12, 'Cocks swordsmen (in lats)', 'Cocks swordsmen (in lats) value'),
(13, 'Cocks with axes (in lats', 'Cocks with axes (in lats value'),
(14, 'Wood', 'Wood value'),
(15, 'Cocks archers', 'Cocks archers value'),
(16, 'Cocks lancers', 'Cocks lancers value'),
(17, 'Gunpowder', 'Gunpowder value'),
(18, 'Cocks gunners', 'Cocks gunners value'),
(19, 'Cocks with bazookas', 'Cocks with bazookas value'),
(20, 'Mana', 'Mana value'),
(21, 'Cocks magicians', 'Cocks magicians value'),
(22, 'Cocks prophets', 'Cocks prophets value'),
(23, 'Experience', 'Experience value'),
(24, 'Cockiness', 'Cockiness value');